### ISSUE TITLE
Hiding the problem using swipe down gesture - keyboard problem

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-009#100]
Problem with layout after you are hiding the problem using swipe down gesture and then closing the keyboard

**Comment by ITsvetkoFF** [comment]
Proposed solution: hide the keyboard before the swipe actually occurs.

**Comment by earostovtseva** [comment]
Problem was solved by adding new class EcoMapSlidingLayer, that extends wunderlist.SlidingLayer. I overrited method OnTouchEvent, and on the beginning I look for keyboard and hide it. This resolve only part of the problem. If user tap lightly, keyboard hide, but SlidingLayer keep space for keyboard. If user tap strongly, everything is ok... I didnt find a place, where a SlidingLayer's height calculates.
