### ISSUE TITLE
Move filters to Toolbar

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-009#123]
- [x] move settings into new item in the left Navigation Menu
- [x] Move filters as a new icon on the Toolbar
- [x] Handle disappearing of filter icon when map is not visible
- [x] Fix filters icon visibility after dialog disapper

*idea - when map is disabled change filter icon to the map icon

**Comment by sttimchenko** [comment]
Idea\* needs to be discussed in point of  useless.
