### ISSUE TITLE
Move AddProblem away from the DialogFragment

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-009#125]
- [x] move to Fragment from Dialog
- [x] interaction between EcoMapFragment and AddProblemFragment
- [x] add mini Map to AddProblemFragment
- [x] on & off problem mode methods
- [x] onBackPressed

**Comment by daniiltyshchenko** [comment]
- [x] move to Fragment from Dialog
- [x] interaction between EcoMapFragment and AddProblemFragment
- [x] add mini Map to AddProblemFragment
- [x] on & off problem mode methods
- [x] onBackPressed
