### ISSUE TITLE
Authorization System

### ISSUE THREAD

**Issue by daniiltyshchenko** [ITsvetkoFF/Kv-009#13]
- [x] Looking for best practices, examples and other preparations (2 h)
- [x] Create UI prototypes for Login and Registration ~~Activities~~ Fragments (5 h)
- [x] Logic for handling user's data and sending request to server (12 h)
- [x] Logic for getting and handling server's answer (8 h)
- [x] Get and  store cookies for user's session (0.5 h)
- [x] Switching between Login and Registration (0.5 h)
- [x] Auto complete for email field (0.5 h)
- [x] Email and password validation (1 h)
- [x] ProgressDialog while connecting with server (0.5 h)
- [x] Login & Registration in Dialog Fragments (1 h)

**Comment by daniiltischenko** [comment]
- [ ] Create UI prototypes for Login and Registration Activities
- [ ] Logic for handling user's data and sending request to server 
- [ ] Logic for getting and handling server's answer
- [ ] Get and  store cookies for user's session
- [ ] Switching between Login and Registration
- [ ] Auto complete for email field
- [ ] Email and password validation
- [ ] "Forgot your password" and password reset functionality
