### ISSUE TITLE
Handle Google Services availability in MainActivity

### ISSUE THREAD

**Issue by sttimchenko** [ITsvetkoFF/Kv-009#82]
Handle if Google Services is present on device in MainActivity where GoogleMap is initialized.
- [x] check if GoogleMap initialized by not null value
- [x] if value is null, propose to download Google Services from Google Play
- [x] otherwise, show smthing like "we are sorry, but without GS you can't use our app" and close app
  Stackoverflow helpful link: http://stackoverflow.com/questions/11753000/how-to-open-the-google-play-store-directly-from-my-android-application
  Google Play Services link: https://play.google.com/store/apps/details?id=com.google.android.gms

**Comment by RexSplode** [comment]
Google API has it's own checking method. Used it instead ^_^
